#!/usr/bin/env bash
# One-time migration: copy existing local Terraform state to S3 backend.
# Run from repo root: bash backend-config/tf-migrate-state-s3.sh <terraform-dir>
# When prompted "Do you want to copy existing state to the new backend?" type: yes
# Prerequisite: aws sso login

set -e
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

if [ -z "$1" ]; then
  echo "Usage: $0 <terraform-dir>"
  echo "Example: $0 apps/frontend/terraform"
  exit 1
fi
TF_DIR="$1"
if [ ! -d "$TF_DIR" ]; then
  echo "Error: directory not found: $TF_DIR"
  exit 1
fi

# Load AWS credentials into this script's environment
eval $(aws configure export-credentials --format env)
unset AWS_PROFILE

if [ -z "$AWS_ACCESS_KEY_ID" ] || [ -z "$AWS_SECRET_ACCESS_KEY" ]; then
  echo "Error: AWS credentials not set. Run: aws sso login"
  exit 1
fi

# On macOS, work around Go TLS cert verification (x509 OSStatus -26276) by using a PEM bundle
if [ "$(uname -s)" = "Darwin" ]; then
  MAC_CERTS="${TMPDIR:-/tmp}/mac-ca-bundle.$$.pem"
  if security find-certificate -a -p /System/Library/Keychains/SystemRootCertificates.keychain > "$MAC_CERTS" 2>/dev/null && [ -s "$MAC_CERTS" ]; then
    export SSL_CERT_FILE="$MAC_CERTS"
    export AWS_CA_BUNDLE="$MAC_CERTS"
  fi
fi

# Escape for HCL: \ -> \\, " -> \"
escape_hcl() { printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'; }

BACKEND_CONFIG_REL="$(python3 -c "
import os
tf = os.path.normpath('$TF_DIR')
depth = tf.count(os.sep) + (1 if tf else 0)
print('../' * depth + 'backend-config')
" 2>/dev/null)" || BACKEND_CONFIG_REL="../../../backend-config"

CREDS_FILE="$REPO_ROOT/backend-config/dev-with-creds.hcl"
{
  cat "$REPO_ROOT/backend-config/dev.hcl"
  echo ""
  echo "# Temporary credentials (generated by tf-migrate-state-s3.sh)"
  printf 'access_key = "%s"\n' "$(escape_hcl "$AWS_ACCESS_KEY_ID")"
  printf 'secret_key = "%s"\n' "$(escape_hcl "$AWS_SECRET_ACCESS_KEY")"
  printf 'token      = "%s"\n' "$(escape_hcl "$AWS_SESSION_TOKEN")"
} > "$CREDS_FILE"

cd "$TF_DIR"
BACKEND_CONFIG_PATH="$BACKEND_CONFIG_REL/dev-with-creds.hcl"
echo "Migrating local state to S3 in $(pwd)..."
echo "When Terraform asks to copy state to the new backend, type: yes"
echo ""
terraform init -migrate-state -backend-config="$BACKEND_CONFIG_PATH"
echo "Done. Use tf-init-s3.sh for this module from now on."
