#!/bin/bash
# Setup script for Stripe test account configuration in development

set -e

echo "🔧 GoalsGuild Stripe Test Account Setup"
echo "=========================================="
echo ""

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Check if .env file exists
ENV_FILE=".env"
if [ ! -f "$ENV_FILE" ]; then
    echo -e "${YELLOW}⚠️  .env file not found. Creating one...${NC}"
    touch "$ENV_FILE"
fi

echo "This script will help you configure Stripe test account for development."
echo ""
echo "You'll need:"
echo "  1. Stripe test account (https://stripe.com)"
echo "  2. Test mode API keys (from Stripe Dashboard)"
echo "  3. Product Price IDs (created in Stripe Dashboard)"
echo ""

# Function to prompt for input
prompt_input() {
    local prompt="$1"
    local var_name="$2"
    local default_value="$3"
    local is_secret="${4:-false}"
    
    if [ -n "$default_value" ]; then
        read -p "$prompt [$default_value]: " value
        value="${value:-$default_value}"
    else
        if [ "$is_secret" = "true" ]; then
            read -sp "$prompt: " value
            echo ""
        else
            read -p "$prompt: " value
        fi
    fi
    
    echo "$value"
}

# Get Stripe Secret Key
echo "📝 Step 1: Stripe API Keys"
echo "---------------------------"
echo "Get these from: Stripe Dashboard → Developers → API keys (Test mode)"
echo ""

STRIPE_SECRET_KEY=$(prompt_input "Enter Stripe Secret Key (sk_test_...)" "STRIPE_SECRET_KEY" "" "true")
STRIPE_PUBLISHABLE_KEY=$(prompt_input "Enter Stripe Publishable Key (pk_test_...)" "STRIPE_PUBLISHABLE_KEY" "")

# Get Price IDs
echo ""
echo "📝 Step 2: Product Price IDs"
echo "-----------------------------"
echo "Get these from: Stripe Dashboard → Products → [Product] → Pricing"
echo ""

INITIATE_PRICE_ID=$(prompt_input "Enter INITIATE Price ID (price_...)" "STRIPE_PRICE_ID_INITIATE" "")
JOURNEYMAN_PRICE_ID=$(prompt_input "Enter JOURNEYMAN Price ID (price_...)" "STRIPE_PRICE_ID_JOURNEYMAN" "")
SAGE_PRICE_ID=$(prompt_input "Enter SAGE Price ID (price_...)" "STRIPE_PRICE_ID_SAGE" "")
GUILDMASTER_PRICE_ID=$(prompt_input "Enter GUILDMASTER Price ID (price_...) [optional]" "STRIPE_PRICE_ID_GUILDMASTER" "")

# Get Webhook Secret (optional)
echo ""
echo "📝 Step 3: Webhook Secret (Optional)"
echo "-------------------------------------"
echo "Get this from: Stripe Dashboard → Developers → Webhooks → [Your Endpoint] → Signing secret"
echo ""

read -p "Do you want to configure webhook secret? (y/n) [n]: " configure_webhook
if [[ "$configure_webhook" =~ ^[Yy]$ ]]; then
    STRIPE_WEBHOOK_SECRET=$(prompt_input "Enter Webhook Secret (whsec_...)" "STRIPE_WEBHOOK_SECRET" "" "true")
else
    STRIPE_WEBHOOK_SECRET=""
fi

# Write to .env file
echo ""
echo "💾 Writing configuration to .env file..."
echo ""

# Remove existing Stripe config from .env
sed -i.bak '/^STRIPE_/d' "$ENV_FILE" 2>/dev/null || true
sed -i.bak '/^# Stripe Configuration/d' "$ENV_FILE" 2>/dev/null || true

# Add new configuration
cat >> "$ENV_FILE" << EOF

# Stripe Configuration (Test Mode)
# Generated by setup-stripe-dev.sh
STRIPE_SECRET_KEY=$STRIPE_SECRET_KEY
STRIPE_PUBLISHABLE_KEY=$STRIPE_PUBLISHABLE_KEY
STRIPE_PRICE_ID_INITIATE=$INITIATE_PRICE_ID
STRIPE_PRICE_ID_JOURNEYMAN=$JOURNEYMAN_PRICE_ID
STRIPE_PRICE_ID_SAGE=$SAGE_PRICE_ID
EOF

if [ -n "$GUILDMASTER_PRICE_ID" ]; then
    echo "STRIPE_PRICE_ID_GUILDMASTER=$GUILDMASTER_PRICE_ID" >> "$ENV_FILE"
fi

if [ -n "$STRIPE_WEBHOOK_SECRET" ]; then
    echo "STRIPE_WEBHOOK_SECRET=$STRIPE_WEBHOOK_SECRET" >> "$ENV_FILE"
fi

# Clean up backup file
rm -f "${ENV_FILE}.bak" 2>/dev/null || true

echo -e "${GREEN}✅ Configuration saved to .env file${NC}"
echo ""

# Verify configuration
echo "🔍 Verifying configuration..."
echo ""

if [ -z "$STRIPE_SECRET_KEY" ]; then
    echo -e "${RED}❌ STRIPE_SECRET_KEY is not set${NC}"
    exit 1
fi

if [[ ! "$STRIPE_SECRET_KEY" =~ ^sk_test_ ]]; then
    echo -e "${YELLOW}⚠️  Warning: STRIPE_SECRET_KEY doesn't start with 'sk_test_'${NC}"
    echo "   Make sure you're using a TEST mode key, not a LIVE key!"
fi

if [ -z "$STRIPE_PUBLISHABLE_KEY" ]; then
    echo -e "${YELLOW}⚠️  Warning: STRIPE_PUBLISHABLE_KEY is not set${NC}"
fi

if [[ ! "$STRIPE_PUBLISHABLE_KEY" =~ ^pk_test_ ]]; then
    echo -e "${YELLOW}⚠️  Warning: STRIPE_PUBLISHABLE_KEY doesn't start with 'pk_test_'${NC}"
fi

# Check Price IDs
missing_prices=()
if [ -z "$INITIATE_PRICE_ID" ]; then missing_prices+=("INITIATE"); fi
if [ -z "$JOURNEYMAN_PRICE_ID" ]; then missing_prices+=("JOURNEYMAN"); fi
if [ -z "$SAGE_PRICE_ID" ]; then missing_prices+=("SAGE"); fi

if [ ${#missing_prices[@]} -gt 0 ]; then
    echo -e "${YELLOW}⚠️  Warning: Missing Price IDs for: ${missing_prices[*]}${NC}"
    echo "   You can add them later or create products in Stripe Dashboard"
fi

echo ""
echo -e "${GREEN}✅ Setup complete!${NC}"
echo ""
echo "📋 Next steps:"
echo "  1. Source the .env file: source .env (or export variables)"
echo "  2. Start the subscription service"
echo "  3. Test the checkout flow with test card: 4242 4242 4242 4242"
echo ""
echo "📚 For more details, see: docs/deployment/SETUP_STRIPE_TEST_ACCOUNT.md"
echo ""
